version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: postgres-manager-backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./backend/configs:/root/configs:ro
      # Mount SSH keys if needed for remote server access
      - ~/.ssh:/root/.ssh:ro
    networks:
      - postgres-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: postgres-manager-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - postgres-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  postgres-manager-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  backend-logs:
    driver: local
